In [129]:
# Importing the Packages

import geopandas as gpd
import pandas as pd
from shapely.geometry import Point
from keplergl import KeplerGl
from matplotlib import pyplot as plt
import seaborn as sns
import folium
import numpy as np

In [130]:
# Importing and reading the files from the data folder 

pedons_df = pd.read_csv('processed_data\pedons_processed.csv', index_col=None)
samples_df = pd.read_csv('processed_data\sample_data_processed.csv', index_col=None)
location_gdf = gpd.read_file('processed_data\general_location_processed.geojson', driver='GeoJSON')

In [131]:
samples_pedons_df = samples_df.merge(pedons_df, on=['upedon', 'rcasiteid'], how='inner')

In [132]:
samples_pedons_df.head()

,samp,rcasiteid,upedon,TOP,BOT,Bulkdensity,SOC_pred1,Texture,fragvolc,c_tot_ncs,n_tot_ncs,s_tot_ncs,caco3,SOCstock5,SOCstock30,SOCstock100,Land_Use
0,C0101F011-1,C0101F01,C0101F011,0,5,0.881002,49.674091,PM,0.0,48.094150,2.401340,0.187482,NaN,169.511025,1076.864591,3805.801642,Forestland
1,C0101F011-2,C0101F01,C0101F011,5,22,0.881002,49.674091,PM,0.0,50.142574,1.621640,0.095915,NaN,169.511025,1076.864591,3805.801642,Forestland
2,C0101F011-3,C0101F01,C0101F011,22,100,0.967665,55.530000,PM,0.0,55.529768,1.177027,0.031538,NaN,169.511025,1076.864591,3805.801642,Forestland
3,C0101W011-1,C0101W01,C0101W011,0,5,0.918831,29.594032,None,0.0,50.992633,3.230560,0.320330,NaN,338.654705,1205.698308,3853.560256,Wetland
4,C0101W011-2,C0101W01,C0101W011,5,25,0.904953,48.090000,PM,0.0,48.089204,2.929916,0.106421,NaN,338.654705,1205.698308,3853.560256,Wetland

In [133]:
location_gdf.rename(columns={'RaCA_Id' : 'rcasiteid'}, inplace=True)

In [134]:
merged_df = location_gdf.merge(samples_pedons_df, how='inner', on='rcasiteid')

In [135]:
len(merged_df) == merged_df['samp'].nunique()

True

In [136]:
base_map1 = KeplerGl(height=800, width=600)
base_map1.add_data(data=merged_df.copy(), name='Merged Data')
base_map1.save_to_html(file_name='MergedGeoDataFrame.html')

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter
Map saved to MergedGeoDataFrame.html!

In [137]:
merged_df['lon'] = merged_df.geometry.apply(lambda p: p.x)
merged_df['lat'] = merged_df.geometry.apply(lambda p: p.y)

In [138]:
merged_df

,rcasiteid,geometry,samp,upedon,TOP,BOT,Bulkdensity,SOC_pred1,Texture,fragvolc,c_tot_ncs,n_tot_ncs,s_tot_ncs,caco3,SOCstock5,SOCstock30,SOCstock100,Land_Use,lon,lat
0,C0107F02,POINT (-124.65000 48.27000),C0107F021-1,C0107F021,0,5,0.953805,55.580000,PM,0.0,53.527267,2.242210,0.185752,NaN,184.885955,627.905363,NaN,Forestland,-124.65,48.27
1,C0107F02,POINT (-124.65000 48.27000),C0107F021-2,C0107F021,5,11,1.200590,37.946338,sil,0.0,51.575090,1.729820,0.211545,NaN,184.885955,627.905363,NaN,Forestland,-124.65,48.27
2,C0107F02,POINT (-124.65000 48.27000),C0107F021-3,C0107F021,11,25,1.111808,6.512871,sicl,5.0,3.445784,0.305839,0.021409,NaN,184.885955,627.905363,NaN,Forestland,-124.65,48.27
3,C0107F02,POINT (-124.65000 48.27000),C0107F021-4,C0107F021,25,40,1.178822,5.701971,l,10.0,3.332542,0.205712,0.024685,0.051788,184.885955,627.905363,NaN,Forestland,-124.65,48.27
4,C0107F02,POINT (-124.65000 48.27000),C0107F021-5,C0107F021,40,50,1.236786,1.482753,l,5.0,1.079146,0.142529,0.010181,NaN,184.885955,627.905363,NaN,Forestland,-124.65,48.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7630,C0114F06,POINT (-122.88000 44.46000),C0114F061-3,C0114F061,11,26,0.882278,4.147951,sil,15.0,3.256266,0.228729,0.021833,0.069461,139.050248,223.893740,391.896903,Forestland,-122.88,44.46
7631,C0114F06,POINT (-122.88000 44.46000),C0114F061-4,C0114F061,26,50,0.916458,4.480949,sicl,10.0,2.639128,0.150600,0.015579,0.069495,139.050248,223.893740,391.896903,Forestland,-122.88,44.46
7632,C0114F06,POINT (-122.88000 44.46000),C0114F061-5,C0114F061,50,76,1.361047,4.984361,sic,5.0,3.050687,0.190148,0.015586,0.125979,139.050248,223.893740,391.896903,Forestland,-122.88,44.46
7633,C0114F06,POINT (-122.88000 44.46000),C0114F061-6,C0114F061,76,94,1.434116,1.883770,sic,5.0,1.012486,0.092233,0.011400,0.107360,139.050248,223.893740,391.896903,Forestland,-122.88,44.46
7634,C0114F06,POINT (-122.88000 44.46000),C0114F061-7,C0114F061,94,100,1.381118,1.323782,sicl,0.0,0.586845,0.031215,0.010405,0.060922,139.050248,223.893740,391.896903,Forestland,-122.88,44.46

In [139]:
base_map1 = KeplerGl(height=800, width=600)
base_map1.add_data(data=merged_df.copy(), name='Merged Data')
base_map1.save_to_html(file_name='MergedGeoDataFrame.html')

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter
Map saved to MergedGeoDataFrame.html!

In [145]:
merged_df.to_file('processed_data\pedon_sample_location.geojson', driver='GeoJSON')

In [140]:
merged_df.isna().any()

rcasiteid      False
geometry       False
samp           False
upedon         False
TOP            False
BOT            False
Bulkdensity     True
SOC_pred1      False
Texture        False
fragvolc       False
c_tot_ncs       True
n_tot_ncs       True
s_tot_ncs       True
caco3           True
SOCstock5       True
SOCstock30      True
SOCstock100     True
Land_Use       False
lon            False
lat            False
dtype: bool

In [141]:
merged_df.dtypes

rcasiteid        object
geometry       geometry
samp             object
upedon           object
TOP               int64
BOT               int64
Bulkdensity     float64
SOC_pred1       float64
Texture          object
fragvolc        float64
c_tot_ncs       float64
n_tot_ncs       float64
s_tot_ncs       float64
caco3           float64
SOCstock5       float64
SOCstock30      float64
SOCstock100     float64
Land_Use         object
lon             float64
lat             float64
dtype: object

In [143]:
merged_df.dropna(inplace=True)

In [144]:
merged_df.isna().sum()

rcasiteid      0
geometry       0
samp           0
upedon         0
TOP            0
BOT            0
Bulkdensity    0
SOC_pred1      0
Texture        0
fragvolc       0
c_tot_ncs      0
n_tot_ncs      0
s_tot_ncs      0
caco3          0
SOCstock5      0
SOCstock30     0
SOCstock100    0
Land_Use       0
lon            0
lat            0
dtype: int64

In [127]:
numeric_columns = merged_df.select_dtypes(exclude=['object', 'geometry'])
numeric_columns

,TOP,BOT,Bulkdensity,SOC_pred1,fragvolc,c_tot_ncs,n_tot_ncs,s_tot_ncs,caco3,SOCstock5,SOCstock30,SOCstock100,lon,lat
0,0,5,0.953805,55.580000,0.0,53.527267,2.242210,0.185752,NaN,184.885955,627.905363,NaN,-124.65,48.27
1,5,11,1.200590,37.946338,0.0,51.575090,1.729820,0.211545,NaN,184.885955,627.905363,NaN,-124.65,48.27
2,11,25,1.111808,6.512871,5.0,3.445784,0.305839,0.021409,NaN,184.885955,627.905363,NaN,-124.65,48.27
3,25,40,1.178822,5.701971,10.0,3.332542,0.205712,0.024685,0.051788,184.885955,627.905363,NaN,-124.65,48.27
4,40,50,1.236786,1.482753,5.0,1.079146,0.142529,0.010181,NaN,184.885955,627.905363,NaN,-124.65,48.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7630,11,26,0.882278,4.147951,15.0,3.256266,0.228729,0.021833,0.069461,139.050248,223.893740,391.896903,-122.88,44.46
7631,26,50,0.916458,4.480949,10.0,2.639128,0.150600,0.015579,0.069495,139.050248,223.893740,391.896903,-122.88,44.46
7632,50,76,1.361047,4.984361,5.0,3.050687,0.190148,0.015586,0.125979,139.050248,223.893740,391.896903,-122.88,44.46
7633,76,94,1.434116,1.883770,5.0,1.012486,0.092233,0.011400,0.107360,139.050248,223.893740,391.896903,-122.88,44.46
7634,94,100,1.381118,1.323782,0.0,0.586845,0.031215,0.010405,0.060922,139.050248,223.893740,391.896903,-122.88,44.46

In [128]:
type(numeric_columns.at[0, 'SOCstock100'])

numpy.float64

In [111]:
from sklearn.impute import KNNImputer
knn_imputer = KNNImputer(n_neighbors=7,missing_values=np.nan)
features_imputed = pd.DataFrame(np.round(knn_imputer.fit_transform(numeric_columns)),columns = numeric_columns.columns, )
features_imputed

,TOP,BOT,Bulkdensity,SOC_pred1,fragvolc,c_tot_ncs,n_tot_ncs,s_tot_ncs,caco3,SOCstock5,SOCstock30,SOCstock100,lon,lat
0,0.0,5.0,1.0,56.0,0.0,54.0,2.0,0.0,1.0,185.0,628.0,845.0,-125.0,48.0
1,5.0,11.0,1.0,38.0,0.0,52.0,2.0,0.0,1.0,185.0,628.0,845.0,-125.0,48.0
2,11.0,25.0,1.0,7.0,5.0,3.0,0.0,0.0,1.0,185.0,628.0,735.0,-125.0,48.0
3,25.0,40.0,1.0,6.0,10.0,3.0,0.0,0.0,0.0,185.0,628.0,735.0,-125.0,48.0
4,40.0,50.0,1.0,1.0,5.0,1.0,0.0,0.0,0.0,185.0,628.0,726.0,-125.0,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7630,11.0,26.0,1.0,4.0,15.0,3.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0
7631,26.0,50.0,1.0,4.0,10.0,3.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0
7632,50.0,76.0,1.0,5.0,5.0,3.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0
7633,76.0,94.0,1.0,2.0,5.0,1.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0
7634,94.0,100.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0

In [69]:
features_imputed.isna().any()

TOP            False
BOT            False
Bulkdensity    False
SOC_pred1      False
fragvolc       False
c_tot_ncs      False
n_tot_ncs      False
s_tot_ncs      False
caco3          False
SOCstock5      False
SOCstock30     False
SOCstock100    False
lon            False
lat            False
dtype: bool

In [70]:
merged_df.drop(columns=numeric_columns.columns, inplace=True)

In [72]:
merged_df.join(features_imputed)

,rcasiteid,geometry,samp,upedon,Texture,Land_Use,TOP,BOT,Bulkdensity,SOC_pred1,fragvolc,c_tot_ncs,n_tot_ncs,s_tot_ncs,caco3,SOCstock5,SOCstock30,SOCstock100,lon,lat
0,C0107F02,POINT (-124.65000 48.27000),C0107F021-1,C0107F021,PM,Forestland,0.0,5.0,1.0,56.0,0.0,54.0,2.0,0.0,1.0,185.0,628.0,845.0,-125.0,48.0
1,C0107F02,POINT (-124.65000 48.27000),C0107F021-2,C0107F021,sil,Forestland,5.0,11.0,1.0,38.0,0.0,52.0,2.0,0.0,1.0,185.0,628.0,845.0,-125.0,48.0
2,C0107F02,POINT (-124.65000 48.27000),C0107F021-3,C0107F021,sicl,Forestland,11.0,25.0,1.0,7.0,5.0,3.0,0.0,0.0,1.0,185.0,628.0,735.0,-125.0,48.0
3,C0107F02,POINT (-124.65000 48.27000),C0107F021-4,C0107F021,l,Forestland,25.0,40.0,1.0,6.0,10.0,3.0,0.0,0.0,0.0,185.0,628.0,735.0,-125.0,48.0
4,C0107F02,POINT (-124.65000 48.27000),C0107F021-5,C0107F021,l,Forestland,40.0,50.0,1.0,1.0,5.0,1.0,0.0,0.0,0.0,185.0,628.0,726.0,-125.0,48.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7630,C0114F06,POINT (-122.88000 44.46000),C0114F061-3,C0114F061,sil,Forestland,11.0,26.0,1.0,4.0,15.0,3.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0
7631,C0114F06,POINT (-122.88000 44.46000),C0114F061-4,C0114F061,sicl,Forestland,26.0,50.0,1.0,4.0,10.0,3.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0
7632,C0114F06,POINT (-122.88000 44.46000),C0114F061-5,C0114F061,sic,Forestland,50.0,76.0,1.0,5.0,5.0,3.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0
7633,C0114F06,POINT (-122.88000 44.46000),C0114F061-6,C0114F061,sic,Forestland,76.0,94.0,1.0,2.0,5.0,1.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0
7634,C0114F06,POINT (-122.88000 44.46000),C0114F061-7,C0114F061,sicl,Forestland,94.0,100.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,139.0,224.0,392.0,-123.0,44.0

In [ ]:
sns.pairplot(joined, hue='Land_Use')